name: Testes do Projeto

on:
  push:
    branches:
      - jpa-adaptado
      - bd2
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Verificar versão do Maven
        run: mvn --version

      - name: Executar testes com Maven
        run: mvn clean test
